### ISSUE TITLE
Add support for SSH "checkPeriod" option

### ISSUE THREAD

**Issue by MaxwellSchmidt97** [jsiebens/ionscale#14]
Hello,

After submitting [this issue](https://github.com/jsiebens/ionscale/issues/6) you made a first implementation very quickly, props for that.

The only thing holding back security in our organisation has been the missing SSH "checkPeriod" option as logging in every time you get disconnected from a server is a no-go for us.
Are you still planning to add the implementation for this feature? If so, do you have an ETA?

Thank you again for creating this project, it has already been very useful for us.

Cheers,
Max

**Comment by jsiebens** [comment]
Hi @MaxwellSchmidt97 

Thanks for the feedback.

The "checkPeriod" is indeed not yet supported. 
It is still something I would like to add, but I won't be able to work on it anytime soon, so I won't commit to any ETA.

**Comment by jsiebens** [comment]
added with PR #21
