### ISSUE TITLE
Tailscale Serve

### ISSUE THREAD

**Issue by Haxverse** [jsiebens/ionscale#18]
Hello,

The [`tailscale serve`](https://tailscale.com/kb/1312/serve) command seems to use a [control server endpoint](https://github.com/tailscale/tailscale/blob/main/ipn/localapi/localapi.go#L2242-L2300) that is not implemented in ionscale.

Can this be added?

Thanks a lot,
Mr. Hax

**Comment by jsiebens** [comment]
available in release [v0.10.0-rc1](https://github.com/jsiebens/ionscale/releases/tag/v0.10.0-rc1) and [v0.10.0](https://github.com/jsiebens/ionscale/releases/tag/v0.10.0)
