### ISSUE TITLE
Unexpected error: sql transaction committed or rolled back

### ISSUE THREAD

**Issue by vinhjaxt** [jsiebens/ionscale#28]
![image](https://github.com/jsiebens/ionscale/assets/8877695/397f22f1-ab77-439a-a829-868f26657002)

Hi jsiebens,

I dont know why ionscale throw this exception, please help me check this out.

Thank you!

**Comment by jsiebens** [comment]
Hi,

Can you provide some more details on how to reproduce this error?

**Comment by vinhjaxt** [comment]
I wish I could, but I do a lot of connecting/disconnecting, logging (via SSO/OIDC), when I look at the logs, It's there.
