### ISSUE TITLE
Unexpected error: nil pointer dereference

### ISSUE THREAD

**Issue by vinhjaxt** [jsiebens/ionscale#29]
![image](https://github.com/jsiebens/ionscale/assets/8877695/8cef4c53-9aae-40b8-b343-bb94a59680ab)

When no tailnet defined.

**Comment by jsiebens** [comment]
Hi,

Can you provide some more details on how to reproduce this error?

**Comment by vinhjaxt** [comment]
Sure, this is my steps:

```
1. Start ionscale with oidc and no tailnets defined
2. Login to tailscale using SSO/OIDC
3. Error raised
```

**Comment by jsiebens** [comment]
Hi,

I'm not able te reproduce the error. What versions of ionscale/tailscale are you using?
