### ISSUE TITLE
v0.15.0 seems to have broken DERP-relayed traffic

### ISSUE THREAD

**Issue by Haxverse** [jsiebens/ionscale#59]
Hello,

It seems that since version v0.15.0, unless a direct connection is able to be established, traffic does not reach the destination. In other words, DERP-relayed traffic does not work.

The weird thing is that disco pings do get through; so `tailscale ping external-device` does show a relayed response, while `ping external-device` does not.

It would be great if someone can provide a solution, and/or can confirm my issue.

Thanks a lot,
Mr. Hax

**Comment by jsiebens** [comment]
Version v0.15.0 introduces an embedded DERP server, which is enabled by default. (see [notes](https://github.com/jsiebens/ionscale/releases/tag/v0.15.0))
Have you disabled this feature? If enabled, are all required ports of the embedded DERP open to the internet?
