### ISSUE TITLE
Add Tailscale SSH support to ACLs

### ISSUE THREAD

**Issue by MaxwellSchmidt97** [jsiebens/ionscale#6]
Hello,

First of all, this seems like a much more polished project than headscale is in it's current state. Props for that.
My question is if/when the [Tailscale SSH](https://tailscale.com/kb/1193/tailscale-ssh/) feature is planned. This will allow for SSH access as part of ACLs. We would love to use this feature.

Cheers,
Max

**Comment by jsiebens** [comment]
A first implentation is now available in `v0.4.0-rc1`
